version: '3.1'

services:

  public-postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 3432:5432
    volumes:
      - database_folder:/var/lib/postgresql/data

volumes:
  database_folder:
    external:
      name: public_posgres_database